package com.hc.rpc.serialization;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trans.proto

public final class Trans {
  private Trans() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface event_dataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:event_data)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *注意，1-16占1个字节，16以上占2个字节，如果要扩展字段且超过了16个，尽量把常用字段放到1-16里.使用sfixed定长int替代可变长int
     *必填，消息类型
     * </pre>
     *
     * <code>sfixed32 type = 1;</code>
     */
    int getType();

    /**
     * <pre>
     *必填，消息流水号
     * </pre>
     *
     * <code>string serialNumber = 2;</code>
     */
    String getSerialNumber();
    /**
     * <pre>
     *必填，消息流水号
     * </pre>
     *
     * <code>string serialNumber = 2;</code>
     */
    com.google.protobuf.ByteString
        getSerialNumberBytes();

    /**
     * <pre>
     *必填，时间戳
     * </pre>
     *
     * <code>sfixed64 timeStamp = 3;</code>
     */
    long getTimeStamp();

    /**
     * <pre>
     *必填，connector节点ID
     * </pre>
     *
     * <code>string nodeArtifactId = 4;</code>
     */
    String getNodeArtifactId();
    /**
     * <pre>
     *必填，connector节点ID
     * </pre>
     *
     * <code>string nodeArtifactId = 4;</code>
     */
    com.google.protobuf.ByteString
        getNodeArtifactIdBytes();

    /**
     * <code>string eqId = 5;</code>
     */
    String getEqId();
    /**
     * <code>string eqId = 5;</code>
     */
    com.google.protobuf.ByteString
        getEqIdBytes();

    /**
     * <code>sfixed32 eqType = 6;</code>
     */
    int getEqType();

    /**
     * <code>string dispatcherId = 7;</code>
     */
    String getDispatcherId();
    /**
     * <code>string dispatcherId = 7;</code>
     */
    com.google.protobuf.ByteString
        getDispatcherIdBytes();

    /**
     * <code>sfixed32 protocol = 8;</code>
     */
    int getProtocol();

    /**
     * <code>string msg = 9;</code>
     */
    String getMsg();
    /**
     * <code>string msg = 9;</code>
     */
    com.google.protobuf.ByteString
        getMsgBytes();

    /**
     * <code>string uri = 10;</code>
     */
    String getUri();
    /**
     * <code>string uri = 10;</code>
     */
    com.google.protobuf.ByteString
        getUriBytes();

    /**
     * <code>sfixed32 qos = 11;</code>
     */
    int getQos();

    /**
     * <code>sfixed32 reTryTimeout = 12;</code>
     */
    int getReTryTimeout();
  }
  /**
   * Protobuf type {@code event_data}
   */
  public  static final class event_data extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:event_data)
      event_dataOrBuilder {


    public String asString() {
      return "event_data{" +
              "type_=" + type_ +
              ", serialNumber_=" + serialNumber_ +
              ", timeStamp_=" + timeStamp_ +
              ", nodeArtifactId_=" + nodeArtifactId_ +
              ", eqId_=" + eqId_ +
              ", eqType_=" + eqType_ +
              ", dispatcherId_=" + dispatcherId_ +
              ", protocol_=" + protocol_ +
              ", msg_=" + msg_ +
              ", uri_=" + uri_ +
              ", qos_=" + qos_ +
              ", reTryTimeout_=" + reTryTimeout_ +
              ", memoizedIsInitialized=" + memoizedIsInitialized +
              '}';
    }

    private static final long serialVersionUID = 0L;
    // Use event_data.newBuilder() to construct.
    private event_data(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private event_data() {
      type_ = 0;
      serialNumber_ = "";
      timeStamp_ = 0L;
      nodeArtifactId_ = "";
      eqId_ = "";
      eqType_ = 0;
      dispatcherId_ = "";
      protocol_ = 0;
      msg_ = "";
      uri_ = "";
      qos_ = 0;
      reTryTimeout_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private event_data(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 13: {

              type_ = input.readSFixed32();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              serialNumber_ = s;
              break;
            }
            case 25: {

              timeStamp_ = input.readSFixed64();
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              nodeArtifactId_ = s;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              eqId_ = s;
              break;
            }
            case 53: {

              eqType_ = input.readSFixed32();
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();

              dispatcherId_ = s;
              break;
            }
            case 69: {

              protocol_ = input.readSFixed32();
              break;
            }
            case 74: {
              String s = input.readStringRequireUtf8();

              msg_ = s;
              break;
            }
            case 82: {
              String s = input.readStringRequireUtf8();

              uri_ = s;
              break;
            }
            case 93: {

              qos_ = input.readSFixed32();
              break;
            }
            case 101: {

              reTryTimeout_ = input.readSFixed32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Trans.internal_static_event_data_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Trans.internal_static_event_data_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              event_data.class, Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <pre>
     *注意，1-16占1个字节，16以上占2个字节，如果要扩展字段且超过了16个，尽量把常用字段放到1-16里.使用sfixed定长int替代可变长int
     *必填，消息类型
     * </pre>
     *
     * <code>sfixed32 type = 1;</code>
     */
    public int getType() {
      return type_;
    }

    public static final int SERIALNUMBER_FIELD_NUMBER = 2;
    private volatile Object serialNumber_;
    /**
     * <pre>
     *必填，消息流水号
     * </pre>
     *
     * <code>string serialNumber = 2;</code>
     */
    public String getSerialNumber() {
      Object ref = serialNumber_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        serialNumber_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *必填，消息流水号
     * </pre>
     *
     * <code>string serialNumber = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSerialNumberBytes() {
      Object ref = serialNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        serialNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    private long timeStamp_;
    /**
     * <pre>
     *必填，时间戳
     * </pre>
     *
     * <code>sfixed64 timeStamp = 3;</code>
     */
    public long getTimeStamp() {
      return timeStamp_;
    }

    public static final int NODEARTIFACTID_FIELD_NUMBER = 4;
    private volatile Object nodeArtifactId_;
    /**
     * <pre>
     *必填，connector节点ID
     * </pre>
     *
     * <code>string nodeArtifactId = 4;</code>
     */
    public String getNodeArtifactId() {
      Object ref = nodeArtifactId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        nodeArtifactId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *必填，connector节点ID
     * </pre>
     *
     * <code>string nodeArtifactId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getNodeArtifactIdBytes() {
      Object ref = nodeArtifactId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        nodeArtifactId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EQID_FIELD_NUMBER = 5;
    private volatile Object eqId_;
    /**
     * <code>string eqId = 5;</code>
     */
    public String getEqId() {
      Object ref = eqId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        eqId_ = s;
        return s;
      }
    }
    /**
     * <code>string eqId = 5;</code>
     */
    public com.google.protobuf.ByteString
        getEqIdBytes() {
      Object ref = eqId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        eqId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EQTYPE_FIELD_NUMBER = 6;
    private int eqType_;
    /**
     * <code>sfixed32 eqType = 6;</code>
     */
    public int getEqType() {
      return eqType_;
    }

    public static final int DISPATCHERID_FIELD_NUMBER = 7;
    private volatile Object dispatcherId_;
    /**
     * <code>string dispatcherId = 7;</code>
     */
    public String getDispatcherId() {
      Object ref = dispatcherId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        dispatcherId_ = s;
        return s;
      }
    }
    /**
     * <code>string dispatcherId = 7;</code>
     */
    public com.google.protobuf.ByteString
        getDispatcherIdBytes() {
      Object ref = dispatcherId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        dispatcherId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROTOCOL_FIELD_NUMBER = 8;
    private int protocol_;
    /**
     * <code>sfixed32 protocol = 8;</code>
     */
    public int getProtocol() {
      return protocol_;
    }

    public static final int MSG_FIELD_NUMBER = 9;
    private volatile Object msg_;
    /**
     * <code>string msg = 9;</code>
     */
    public String getMsg() {
      Object ref = msg_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        msg_ = s;
        return s;
      }
    }
    /**
     * <code>string msg = 9;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      Object ref = msg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int URI_FIELD_NUMBER = 10;
    private volatile Object uri_;
    /**
     * <code>string uri = 10;</code>
     */
    public String getUri() {
      Object ref = uri_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        uri_ = s;
        return s;
      }
    }
    /**
     * <code>string uri = 10;</code>
     */
    public com.google.protobuf.ByteString
        getUriBytes() {
      Object ref = uri_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        uri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int QOS_FIELD_NUMBER = 11;
    private int qos_;
    /**
     * <code>sfixed32 qos = 11;</code>
     */
    public int getQos() {
      return qos_;
    }

    public static final int RETRYTIMEOUT_FIELD_NUMBER = 12;
    private int reTryTimeout_;
    /**
     * <code>sfixed32 reTryTimeout = 12;</code>
     */
    public int getReTryTimeout() {
      return reTryTimeout_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != 0) {
        output.writeSFixed32(1, type_);
      }
      if (!getSerialNumberBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, serialNumber_);
      }
      if (timeStamp_ != 0L) {
        output.writeSFixed64(3, timeStamp_);
      }
      if (!getNodeArtifactIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, nodeArtifactId_);
      }
      if (!getEqIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, eqId_);
      }
      if (eqType_ != 0) {
        output.writeSFixed32(6, eqType_);
      }
      if (!getDispatcherIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, dispatcherId_);
      }
      if (protocol_ != 0) {
        output.writeSFixed32(8, protocol_);
      }
      if (!getMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, msg_);
      }
      if (!getUriBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, uri_);
      }
      if (qos_ != 0) {
        output.writeSFixed32(11, qos_);
      }
      if (reTryTimeout_ != 0) {
        output.writeSFixed32(12, reTryTimeout_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSFixed32Size(1, type_);
      }
      if (!getSerialNumberBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, serialNumber_);
      }
      if (timeStamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeSFixed64Size(3, timeStamp_);
      }
      if (!getNodeArtifactIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, nodeArtifactId_);
      }
      if (!getEqIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, eqId_);
      }
      if (eqType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSFixed32Size(6, eqType_);
      }
      if (!getDispatcherIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, dispatcherId_);
      }
      if (protocol_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSFixed32Size(8, protocol_);
      }
      if (!getMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, msg_);
      }
      if (!getUriBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, uri_);
      }
      if (qos_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSFixed32Size(11, qos_);
      }
      if (reTryTimeout_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSFixed32Size(12, reTryTimeout_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof event_data)) {
        return super.equals(obj);
      }
      event_data other = (event_data) obj;

      boolean result = true;
      result = result && (getType()
          == other.getType());
      result = result && getSerialNumber()
          .equals(other.getSerialNumber());
      result = result && (getTimeStamp()
          == other.getTimeStamp());
      result = result && getNodeArtifactId()
          .equals(other.getNodeArtifactId());
      result = result && getEqId()
          .equals(other.getEqId());
      result = result && (getEqType()
          == other.getEqType());
      result = result && getDispatcherId()
          .equals(other.getDispatcherId());
      result = result && (getProtocol()
          == other.getProtocol());
      result = result && getMsg()
          .equals(other.getMsg());
      result = result && getUri()
          .equals(other.getUri());
      result = result && (getQos()
          == other.getQos());
      result = result && (getReTryTimeout()
          == other.getReTryTimeout());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (37 * hash) + SERIALNUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getSerialNumber().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimeStamp());
      hash = (37 * hash) + NODEARTIFACTID_FIELD_NUMBER;
      hash = (53 * hash) + getNodeArtifactId().hashCode();
      hash = (37 * hash) + EQID_FIELD_NUMBER;
      hash = (53 * hash) + getEqId().hashCode();
      hash = (37 * hash) + EQTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getEqType();
      hash = (37 * hash) + DISPATCHERID_FIELD_NUMBER;
      hash = (53 * hash) + getDispatcherId().hashCode();
      hash = (37 * hash) + PROTOCOL_FIELD_NUMBER;
      hash = (53 * hash) + getProtocol();
      hash = (37 * hash) + MSG_FIELD_NUMBER;
      hash = (53 * hash) + getMsg().hashCode();
      hash = (37 * hash) + URI_FIELD_NUMBER;
      hash = (53 * hash) + getUri().hashCode();
      hash = (37 * hash) + QOS_FIELD_NUMBER;
      hash = (53 * hash) + getQos();
      hash = (37 * hash) + RETRYTIMEOUT_FIELD_NUMBER;
      hash = (53 * hash) + getReTryTimeout();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static event_data parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static event_data parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static event_data parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static event_data parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static event_data parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static event_data parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static event_data parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static event_data parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static event_data parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static event_data parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static event_data parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static event_data parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(event_data prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code event_data}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:event_data)
        event_dataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Trans.internal_static_event_data_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Trans.internal_static_event_data_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                event_data.class, Builder.class);
      }

      // Construct using Trans.event_data.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;

        serialNumber_ = "";

        timeStamp_ = 0L;

        nodeArtifactId_ = "";

        eqId_ = "";

        eqType_ = 0;

        dispatcherId_ = "";

        protocol_ = 0;

        msg_ = "";

        uri_ = "";

        qos_ = 0;

        reTryTimeout_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Trans.internal_static_event_data_descriptor;
      }

      public event_data getDefaultInstanceForType() {
        return event_data.getDefaultInstance();
      }

      public event_data build() {
        event_data result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public event_data buildPartial() {
        event_data result = new event_data(this);
        result.type_ = type_;
        result.serialNumber_ = serialNumber_;
        result.timeStamp_ = timeStamp_;
        result.nodeArtifactId_ = nodeArtifactId_;
        result.eqId_ = eqId_;
        result.eqType_ = eqType_;
        result.dispatcherId_ = dispatcherId_;
        result.protocol_ = protocol_;
        result.msg_ = msg_;
        result.uri_ = uri_;
        result.qos_ = qos_;
        result.reTryTimeout_ = reTryTimeout_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof event_data) {
          return mergeFrom((event_data)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(event_data other) {
        if (other == event_data.getDefaultInstance()) return this;
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (!other.getSerialNumber().isEmpty()) {
          serialNumber_ = other.serialNumber_;
          onChanged();
        }
        if (other.getTimeStamp() != 0L) {
          setTimeStamp(other.getTimeStamp());
        }
        if (!other.getNodeArtifactId().isEmpty()) {
          nodeArtifactId_ = other.nodeArtifactId_;
          onChanged();
        }
        if (!other.getEqId().isEmpty()) {
          eqId_ = other.eqId_;
          onChanged();
        }
        if (other.getEqType() != 0) {
          setEqType(other.getEqType());
        }
        if (!other.getDispatcherId().isEmpty()) {
          dispatcherId_ = other.dispatcherId_;
          onChanged();
        }
        if (other.getProtocol() != 0) {
          setProtocol(other.getProtocol());
        }
        if (!other.getMsg().isEmpty()) {
          msg_ = other.msg_;
          onChanged();
        }
        if (!other.getUri().isEmpty()) {
          uri_ = other.uri_;
          onChanged();
        }
        if (other.getQos() != 0) {
          setQos(other.getQos());
        }
        if (other.getReTryTimeout() != 0) {
          setReTryTimeout(other.getReTryTimeout());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        event_data parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (event_data) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ ;
      /**
       * <pre>
       *注意，1-16占1个字节，16以上占2个字节，如果要扩展字段且超过了16个，尽量把常用字段放到1-16里.使用sfixed定长int替代可变长int
       *必填，消息类型
       * </pre>
       *
       * <code>sfixed32 type = 1;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <pre>
       *注意，1-16占1个字节，16以上占2个字节，如果要扩展字段且超过了16个，尽量把常用字段放到1-16里.使用sfixed定长int替代可变长int
       *必填，消息类型
       * </pre>
       *
       * <code>sfixed32 type = 1;</code>
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *注意，1-16占1个字节，16以上占2个字节，如果要扩展字段且超过了16个，尽量把常用字段放到1-16里.使用sfixed定长int替代可变长int
       *必填，消息类型
       * </pre>
       *
       * <code>sfixed32 type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private Object serialNumber_ = "";
      /**
       * <pre>
       *必填，消息流水号
       * </pre>
       *
       * <code>string serialNumber = 2;</code>
       */
      public String getSerialNumber() {
        Object ref = serialNumber_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          serialNumber_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *必填，消息流水号
       * </pre>
       *
       * <code>string serialNumber = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSerialNumberBytes() {
        Object ref = serialNumber_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          serialNumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *必填，消息流水号
       * </pre>
       *
       * <code>string serialNumber = 2;</code>
       */
      public Builder setSerialNumber(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        serialNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *必填，消息流水号
       * </pre>
       *
       * <code>string serialNumber = 2;</code>
       */
      public Builder clearSerialNumber() {
        
        serialNumber_ = getDefaultInstance().getSerialNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *必填，消息流水号
       * </pre>
       *
       * <code>string serialNumber = 2;</code>
       */
      public Builder setSerialNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        serialNumber_ = value;
        onChanged();
        return this;
      }

      private long timeStamp_ ;
      /**
       * <pre>
       *必填，时间戳
       * </pre>
       *
       * <code>sfixed64 timeStamp = 3;</code>
       */
      public long getTimeStamp() {
        return timeStamp_;
      }
      /**
       * <pre>
       *必填，时间戳
       * </pre>
       *
       * <code>sfixed64 timeStamp = 3;</code>
       */
      public Builder setTimeStamp(long value) {
        
        timeStamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *必填，时间戳
       * </pre>
       *
       * <code>sfixed64 timeStamp = 3;</code>
       */
      public Builder clearTimeStamp() {
        
        timeStamp_ = 0L;
        onChanged();
        return this;
      }

      private Object nodeArtifactId_ = "";
      /**
       * <pre>
       *必填，connector节点ID
       * </pre>
       *
       * <code>string nodeArtifactId = 4;</code>
       */
      public String getNodeArtifactId() {
        Object ref = nodeArtifactId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          nodeArtifactId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *必填，connector节点ID
       * </pre>
       *
       * <code>string nodeArtifactId = 4;</code>
       */
      public com.google.protobuf.ByteString
          getNodeArtifactIdBytes() {
        Object ref = nodeArtifactId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          nodeArtifactId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *必填，connector节点ID
       * </pre>
       *
       * <code>string nodeArtifactId = 4;</code>
       */
      public Builder setNodeArtifactId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nodeArtifactId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *必填，connector节点ID
       * </pre>
       *
       * <code>string nodeArtifactId = 4;</code>
       */
      public Builder clearNodeArtifactId() {
        
        nodeArtifactId_ = getDefaultInstance().getNodeArtifactId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *必填，connector节点ID
       * </pre>
       *
       * <code>string nodeArtifactId = 4;</code>
       */
      public Builder setNodeArtifactIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nodeArtifactId_ = value;
        onChanged();
        return this;
      }

      private Object eqId_ = "";
      /**
       * <code>string eqId = 5;</code>
       */
      public String getEqId() {
        Object ref = eqId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          eqId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string eqId = 5;</code>
       */
      public com.google.protobuf.ByteString
          getEqIdBytes() {
        Object ref = eqId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          eqId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string eqId = 5;</code>
       */
      public Builder setEqId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        eqId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string eqId = 5;</code>
       */
      public Builder clearEqId() {
        
        eqId_ = getDefaultInstance().getEqId();
        onChanged();
        return this;
      }
      /**
       * <code>string eqId = 5;</code>
       */
      public Builder setEqIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        eqId_ = value;
        onChanged();
        return this;
      }

      private int eqType_ ;
      /**
       * <code>sfixed32 eqType = 6;</code>
       */
      public int getEqType() {
        return eqType_;
      }
      /**
       * <code>sfixed32 eqType = 6;</code>
       */
      public Builder setEqType(int value) {
        
        eqType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sfixed32 eqType = 6;</code>
       */
      public Builder clearEqType() {
        
        eqType_ = 0;
        onChanged();
        return this;
      }

      private Object dispatcherId_ = "";
      /**
       * <code>string dispatcherId = 7;</code>
       */
      public String getDispatcherId() {
        Object ref = dispatcherId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          dispatcherId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string dispatcherId = 7;</code>
       */
      public com.google.protobuf.ByteString
          getDispatcherIdBytes() {
        Object ref = dispatcherId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          dispatcherId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string dispatcherId = 7;</code>
       */
      public Builder setDispatcherId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        dispatcherId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string dispatcherId = 7;</code>
       */
      public Builder clearDispatcherId() {
        
        dispatcherId_ = getDefaultInstance().getDispatcherId();
        onChanged();
        return this;
      }
      /**
       * <code>string dispatcherId = 7;</code>
       */
      public Builder setDispatcherIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        dispatcherId_ = value;
        onChanged();
        return this;
      }

      private int protocol_ ;
      /**
       * <code>sfixed32 protocol = 8;</code>
       */
      public int getProtocol() {
        return protocol_;
      }
      /**
       * <code>sfixed32 protocol = 8;</code>
       */
      public Builder setProtocol(int value) {
        
        protocol_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sfixed32 protocol = 8;</code>
       */
      public Builder clearProtocol() {
        
        protocol_ = 0;
        onChanged();
        return this;
      }

      private Object msg_ = "";
      /**
       * <code>string msg = 9;</code>
       */
      public String getMsg() {
        Object ref = msg_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string msg = 9;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string msg = 9;</code>
       */
      public Builder setMsg(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string msg = 9;</code>
       */
      public Builder clearMsg() {
        
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>string msg = 9;</code>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msg_ = value;
        onChanged();
        return this;
      }

      private Object uri_ = "";
      /**
       * <code>string uri = 10;</code>
       */
      public String getUri() {
        Object ref = uri_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          uri_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string uri = 10;</code>
       */
      public com.google.protobuf.ByteString
          getUriBytes() {
        Object ref = uri_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          uri_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string uri = 10;</code>
       */
      public Builder setUri(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        uri_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string uri = 10;</code>
       */
      public Builder clearUri() {
        
        uri_ = getDefaultInstance().getUri();
        onChanged();
        return this;
      }
      /**
       * <code>string uri = 10;</code>
       */
      public Builder setUriBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        uri_ = value;
        onChanged();
        return this;
      }

      private int qos_ ;
      /**
       * <code>sfixed32 qos = 11;</code>
       */
      public int getQos() {
        return qos_;
      }
      /**
       * <code>sfixed32 qos = 11;</code>
       */
      public Builder setQos(int value) {
        
        qos_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sfixed32 qos = 11;</code>
       */
      public Builder clearQos() {
        
        qos_ = 0;
        onChanged();
        return this;
      }

      private int reTryTimeout_ ;
      /**
       * <code>sfixed32 reTryTimeout = 12;</code>
       */
      public int getReTryTimeout() {
        return reTryTimeout_;
      }
      /**
       * <code>sfixed32 reTryTimeout = 12;</code>
       */
      public Builder setReTryTimeout(int value) {
        
        reTryTimeout_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sfixed32 reTryTimeout = 12;</code>
       */
      public Builder clearReTryTimeout() {
        
        reTryTimeout_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:event_data)
    }

    // @@protoc_insertion_point(class_scope:event_data)
    private static final event_data DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new event_data();
    }

    public static event_data getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<event_data>
        PARSER = new com.google.protobuf.AbstractParser<event_data>() {
      public event_data parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new event_data(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<event_data> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<event_data> getParserForType() {
      return PARSER;
    }

    public event_data getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_event_data_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_event_data_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\013trans.proto\"\336\001\n\nevent_data\022\014\n\004type\030\001 \001" +
      "(\017\022\024\n\014serialNumber\030\002 \001(\t\022\021\n\ttimeStamp\030\003 " +
      "\001(\020\022\026\n\016nodeArtifactId\030\004 \001(\t\022\014\n\004eqId\030\005 \001(" +
      "\t\022\016\n\006eqType\030\006 \001(\017\022\024\n\014dispatcherId\030\007 \001(\t\022" +
      "\020\n\010protocol\030\010 \001(\017\022\013\n\003msg\030\t \001(\t\022\013\n\003uri\030\n " +
      "\001(\t\022\013\n\003qos\030\013 \001(\017\022\024\n\014reTryTimeout\030\014 \001(\017b\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_event_data_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_event_data_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_event_data_descriptor,
        new String[] { "Type", "SerialNumber", "TimeStamp", "NodeArtifactId", "EqId", "EqType", "DispatcherId", "Protocol", "Msg", "Uri", "Qos", "ReTryTimeout", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
