logging:
  level:
      com.hc: debug
  file: ./log/dispatcher.log
  root: DEBUG
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.105.125.26:3306/device_message_queue?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: hc_test
    password: HCtest123!
  jpa:
      properties:
        hibernate:
          hbm2ddl:
            auto: update
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
dispatcher:
  commons:
    dispatcherId: dispatcher_1
    defaultTimeout: 6000
    host: 0.0.0.0
    httpPort: 8888
    maxHTTPIdleTime: 5000
    mqEventQueueSize: 1000
    maxBusBlockingTime: 1500
  redis:
    maxTotal: 100
    maxIdle: 10
    maxWaitMills: 180000
    testOnBorrow: true
    address: 39.105.125.26
    port: 6379
    maxWait: 3000
    auth: qweasdzxc~!@#
    databaseIndex: 5
    timeBetweenEvictionRunsMillis: 30000
    numTestsPerEvictionRun: 10
    minEvictableIdleTimeMillis: 90000
    keyExpire: 180
  rabbitmq:
    mqHost: 39.105.125.26
    mqPort: 5672
    mqUserName: admin
    mqPwd: 12345678
    virtualHost: /
    upQueueName: upstream
    exchangeName: device_communication


